name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.pair.elixir}} | Erlang/OTP ${{matrix.pair.otp}})
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.12.3
              otp: 24.0.6
          - pair:
              elixir: 1.7.4
              otp: 19.3.6
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Run PostgreSQL
        run: |
          docker run --env POSTGRES_USER=postgres \
            --env POSTGRES_DB=ecto_psql_extras_test \
            --env POSTGRES_PASSWORD=postgres \
            -d -p 5432:5432 postgres:12.5-alpine \
            postgres -c shared_preload_libraries=pg_stat_statements \
            -c pg_stat_statements.track=all \
            -c max_connections=200
          sleep 5
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - name: Run tests
        env:
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_DB: ecto_psql_extras_test
          POSTGRES_PASSWORD: postgres
        run: |
          sleep 4 # wait pg
          mix test --include distribution
